server:
  port: 8084

spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.159.128
    virtual-host: /mall
    username: mall
    password: mall

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5      # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15  # 10秒不发送就过期